### ISSUE TITLE
ERROR: Repository docker-controller not found

### ISSUE THREAD

**Issue by gabber12** [codespaces-io/codespaces#1]
Hey i am getting this error on branch `master`
> Pulling docker (docker-controller:latest)...
> ERROR: repository docker-controller not found: does not exist or no pull access

**Comment by initcron** [comment]
@gabber12 we are yet to test all the images, please help us do so.  Things should become stable preferably after Monday, 20/2.     @vijayboopathy please test and fix the images.

**Comment by vijayboopathy** [comment]
We have not pushed this image to Docker Hub yet ... We are working on it.
Please check after couple of hours.

On Feb 18, 2017 5:10 PM, "Gourav Shah" <notifications@github.com> wrote:

Assigned #1 <https://github.com/codespaces-io/codespaces/issues/1> to
@vijayboopathy <https://github.com/vijayboopathy>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/codespaces-io/codespaces/issues/1#event-967977148>, or mute
the thread

**Comment by gabber12** [comment]
Thanks i'll love to contribute. Though i think its important to create issues so that someone can easily pick them up. Also for codespaces all repos is there some channel where you guys communicate?

**Comment by vijayboopathy** [comment]
Hey @gabber12 . Docker compose file has been updated. Please give it a go now.

**Comment by gabber12** [comment]
Working now 👍

**Comment by vijayboopathy** [comment]
@gabber12 👍
